### ISSUE TITLE
update for scrape.population.distribution

### ISSUE THREAD

**Issue by gheemony** [elishayer/mRchmadness#28]
The current version of the function is limited up to 2019. 

I believe the simple fix is to add 2021 to the filter by year: 
`if (!(year %in% c(2016, 2017, 2018, 2019, 2021)))`

**Comment by elishayer** [comment]
Yes, that works code-wise. I did that yesterday locally to verify the scraper is functional with the current site, and it is. There's a second step of mapping the team names (because they do not provide IDs and use non-standard names) that's needed before it's functional, which I got halfway through yesterday and didn't finish up. I was going to commit that all together so no one else also has to do that mapping. I plan to commit that today.
