### ISSUE TITLE
Upload 2022 population pick distribution

### ISSUE THREAD

**Issue by elishayer** [elishayer/mRchmadness#31]
Splitting off from https://github.com/elishayer/mRchmadness/issues/30 given the different timeline

**Comment by rmassemich** [comment]
I'm sure you're on it already, but I saw that pop picks are up on ESPN now.

**Comment by gheemony** [comment]
Are the pop picks now available?

**Comment by rmassemich** [comment]
I've been trying to make this work by forking and changing the 2021 data in the package to the current data (including the scraped 2022 pop distributions) under the same names. I'm running into the same issue someone else was running into in find.bracket . Hope this works before brackets lock tomorrow...

Finding your bracket ...
  Simulating 1000 pools of size 20 ...Warning: non-unique value when setting 'row.names': ‘NA’
Error in `.rowNamesDF<-`(x, value = value) : 
  duplicate 'row.names' are not allowed

**Comment by cbranch117** [comment]
@rmassemich 

So I did get things to work, best as I could tell, by modifying functions rather than data structures. If you're willing to spend some time digging through what I've done for setting up simulations for the Bradley-Terry matrices, it may be helpful.
I just dropped all my scripts on github, I don't have the time to clean them up for any sort of publication right now.

So all of @elishayer 's original functions are interdependent, and editing one means you need to edit them all (unless you edit the originals, I just changed function names). I included scripts with something like function.bracket_edit.R containing a sim.bracket22 as a function specifically designed to work with 2022 data. 

Sorry in advance for the mess!
https://github.com/cbranch117/mRchmadness_workspace

**Comment by rmassemich** [comment]
@cbranch117 

thanks for doing that. Most of this seems to work, but I'm getting an error 
Error in as.matrix(x)[i] : subscript out of bounds
any time I try to use the find.bracket function
any idea what that might be? I've tried 538 and pop methods.

**Comment by cbranch117** [comment]
Aw man, I don't know if I ever saw that one. I eventually gave up on the 538 and pop models, and just used the matrix.
What worked for me is going through the function script and debugging line by line to find errors. Double check that each part actually creates output.

I wish I had seen this a few weeks ago. The original package is great, but I think the functions are trying to do too much at once. If I have time someday, I'll split into separate functions for prob.matrices and prediction picks, and change how the inputs are processed.
________________________________

**Comment by saberpowers** [comment]
@rmassemich @gheemony @cbranch117 

Thank you for your support of this package last year. We finally got around to closing this issue with PR #37 😂.

I've got another PR (#38) that will update all the data (including 538 predictions and population picks) for 2023 once it's merged into master. We'll continue to update the population picks in the coming days.

Let me know if there's anything I can do to help make this package more useful.
